### ISSUE TITLE
1.77.1 update ruins this fix

### ISSUE THREAD

**Issue by warthog3** [Qusic/Xgress#2]
Just updated today to 1.77.1 and I get the "integrity check failed" message again now. They must have patched or prevented this fix from working.

**Comment by warthog3** [comment]
On an iPhone 5S running iOS 8.1.1 jailbroken.

**Comment by jackalone** [comment]
Confirmed version 1.77.1 breaks Xgress.
Please fix it if possible asap :)

**Comment by warthog3** [comment]
To those interested, an alternative Cydia tweak called "tsProtector 8 alpha" does allow Ingress 1.77.1 to work on jailbroken iOS 8 devices.

https://www.reddit.com/r/Ingress/comments/386cdi/warning_1771_will_not_work_on_jailbroken_iphones/

**Comment by Qusic** [comment]
I can't update the tweak yet because I lost my jailbreak. please use tsProtector. at least for a while.

**Comment by jackalone** [comment]
Thank you very much
Il 04/giu/2015 02:30, "warthog3" notifications@github.com ha scritto:

**Comment by Qusic** [comment]
Fixed.
